device:
  name: bluejay

includes:
  - common/gen6pixel.yml

filters:
  file_inclusions:
    match:
      - vendor/bin/resku_rescue_kicker

synthetic_overlays:
  SettingsGoogleSyntheticOverlay:
    resourcesToInclude:
      string:
        - battery_tip_early_replacement_summary
        - battery_tip_replacement_summary
        - battery_tip_replacement_title
        - charge_cycle_count
        - help_url_battery_replacement

  SystemUIGoogleSyntheticOverlay:
    resourcesToInclude:
      string:
        - battery_health_notify_learn_more
        - battery_management_action
        - battery_replacement_early_notify_des
        - battery_replacement_notify_des
        - battery_replacement_notify_help_url
        - battery_replacement_notify_title
