device:
  name: felix
  build_id: BP1A.250405.007.B1

platform:
  product_makefile: device/google/felix/aosp_felix.mk
  extra_product_system_server_jars:
    - system_ext:felix-services

includes:
  - common/gen7pixel.yml
  - common/gs-wireless-charger.yml
