device:
  name: rango

includes:
  - common/gen10pixel.yml



filters:
  file_inclusions:
    match:
      - system_ext/framework/rango-services.jar
      - vendor/apex/com.google.rango.hardware.threadnetwork.apex

  overlay_inclusions:
    match:
      - com.android.systemui:bool/rango_unfolded_config_use_split_notification_shade = true
      - com.android.systemui:dimen/rango_unfolded_biometric_auth_pattern_view_size = 348.0dp
      - com.android.systemui:dimen/rango_unfolded_control_list_horizontal_spacing = 16.0dp
      - com.android.systemui:dimen/rango_unfolded_control_list_vertical_spacing = 8.0dp
      - com.android.systemui:dimen/rango_unfolded_controls_content_margin_horizontal = 24.0dp
      - com.android.systemui:dimen/rango_unfolded_controls_content_padding = 24.0dp
      - com.android.systemui:dimen/rango_unfolded_controls_header_horizontal_padding = 12.0dp
      - com.android.systemui:dimen/rango_unfolded_controls_panel_corner_radius = 42.0dp
      - com.android.systemui:dimen/rango_unfolded_keyguard_split_shade_top_margin = 68.0dp
      - com.android.systemui:dimen/rango_unfolded_large_screen_shade_header_height = 42.0dp
      - com.android.systemui:dimen/rango_unfolded_large_screen_shade_header_left_padding = @dimen/qs_horizontal_margin
      - com.android.systemui:dimen/rango_unfolded_lockscreen_shade_keyguard_transition_vertical_offset = 83.0dp
      - com.android.systemui:dimen/rango_unfolded_lockscreen_shade_max_over_scroll_amount = 32.0dp
      - com.android.systemui:dimen/rango_unfolded_notification_panel_margin_bottom = 48.0dp
      - com.android.systemui:dimen/rango_unfolded_notification_panel_margin_horizontal = 24.0dp
      - com.android.systemui:dimen/rango_unfolded_notification_section_divider_height = @dimen/notification_side_paddings
      - com.android.systemui:dimen/rango_unfolded_notification_side_paddings = 16.0dp
      - com.android.systemui:dimen/rango_unfolded_qqs_layout_padding_bottom = 16.0dp
      - com.android.systemui:dimen/rango_unfolded_qs_content_horizontal_padding = 24.0dp
      - com.android.systemui:dimen/rango_unfolded_qs_horizontal_margin = 24.0dp
      - com.android.systemui:dimen/rango_unfolded_qs_media_session_height_expanded = 172.0dp
      - com.android.systemui:dimen/rango_unfolded_qs_tiles_page_horizontal_margin = 12.0dp
      - com.android.systemui:dimen/rango_unfolded_split_shade_notifications_scrim_margin_bottom = 16.0dp
      - com.android.systemui:dimen/rango_unfolded_status_bar_icon_horizontal_margin = 0.0sp
      - com.android.systemui:dimen/rango_unfolded_status_view_margin_horizontal = 8.0dp
      - com.android.systemui:integer/rango_unfolded_quick_qs_panel_max_rows = 2
      - com.android.systemui:integer/rango_unfolded_quick_qs_panel_max_tiles = 4
      - com.android.systemui:integer/rango_unfolded_quick_settings_max_rows = 5
      - com.android.systemui:integer/rango_unfolded_quick_settings_num_columns = 2
