device:
  name: raven

platform:
  product_makefile: device/google/raviole/aosp_raven.mk

includes:
  - common/gen6pixel.yml
  - common/gs-wireless-charger.yml

filters:
  sepolicy_dirs:
    match:
      - hardware/google/pixel-sepolicy/vibrator/cs40l26
