device:
  name: tangorpro
  has_cellular: false
  build_id: BP1A.250305.020.T2

platform:
  product_makefile: device/google/tangorpro/aosp_tangorpro.mk

includes:
  - common/gen7pixel.yml

filters:
  overlay_files:
    prefix:
      # DockSetup itself is not shipped
      - DockSetup__auto_generated_rro_
