backport_dirs:
  product:
    - etc/CarrierSettings
  vendor:
    - firmware/brcm
    - firmware/carrierconfig
    - firmware/dauntless
    - firmware/uecapconfig
    - firmware/google
backport_files:
  product:
    - etc/default-permissions/default-permissions.xml # for permissions allowlist
    - etc/permissions/privapp-permissions-google-p.xml # for privapp-permissions allowlist
    - priv-app/EuiccGoogle/EuiccGoogle.apk
  system_ext:
    - app/OemRilHookService/OemRilHookService.apk
    - framework/google-ril.jar
    - framework/oemrilhook.jar
    - lib64/com.google.edgetpu_app_service-V3-ndk.so
    - lib64/com.google.edgetpu_app_service-V4-ndk.so
    - lib64/com.google.edgetpu_vendor_service-V2-ndk.so
    - lib64/vendor.samsung_slsi.telephony.hardware.oemservice@1.0.so
    - lib64/vendor.samsung_slsi.telephony.hardware.radioExternal@1.0.so
    - priv-app/EuiccGoogleOverlay/EuiccGoogleOverlay.apk
    - priv-app/EuiccSupportPixel-P23/EuiccSupportPixel-P23.apk
    - priv-app/EuiccSupportPixel/EuiccSupportPixel.apk
    - priv-app/EuiccSupportPixelPermissions/EuiccSupportPixelPermissions.apk
    - priv-app/OemRilService/OemRilService.apk
    - priv-app/ril-extension/ril-extension.apk
    - priv-app/ShannonIms/ShannonIms.apk
    - priv-app/ShannonRcs/ShannonRcs.apk
  vendor:
    - apex/com.google.pixel.euicc.update.apex
    - bin/hw/android.hardware.neuralnetworks@service-darwinn-aidl
    - bin/hw/rild_exynos
    - bin/hw/vendor.google.edgetpu_vendor_service@1.0-service
    - bin/hw/vendor.google.radioext@1.0-service
    - firmware/1540.app
    - firmware/1540a.app
    - firmware/amss20.bin
    - firmware/aoc.bin
    - firmware/bcmdhd.cal_4383_a3
    - firmware/cs40l20.bin
    - firmware/Data.msc
    - firmware/fw_bcmdhd.bin
    - firmware/fw_bcmdhd.bin_4383_a3
    - firmware/fw_bcmdhd.bin_4390_b1
    - firmware/fw_bcmdhd.bin_4398_d0
    - firmware/fw_bcmdhd.map
    - firmware/fw_bcmdhd.map_4383_a3
    - firmware/fw_bcmdhd.map_4390_b1
    - firmware/fw_bcmdhd.map_4398_d0
    - firmware/g6.app
    - firmware/g7.app
    - firmware/g7a.app
    - firmware/gxp_callisto_fw_core0
    - firmware/gxp_callisto_fw_core1
    - firmware/gxp_callisto_fw_core2
    - firmware/gxp_fw_core0
    - firmware/gxp_fw_core1
    - firmware/gxp_fw_core2
    - firmware/gxp_fw_core3
    - firmware/kepler.bin
    - firmware/mali_csffw-r54p0.bin
    - firmware/ntn_modem/modem.bin
    - firmware/ntn_modem/version.cfg
    - firmware/qm35_fw_pkg.bin
    - firmware/qm35_fw_pkg_prod.bin
    - firmware/st54l_conf.bin
    - lib64/com.google.input-V2-ndk.so
    - lib64/com.google.pixel.modem.logmasklibrary-V1-ndk.so
    - lib64/libdarwinn_hal.so
    - lib64/libedgetpu_client.google.so
    - lib64/libedgetpu_tachyon.google.so
    - lib64/libedgetpu_tflite_compiler.so
    - lib64/libedgetpu_util.so
    - lib64/libgooglerilmemmonitor.so
    - lib64/libgril_oem-google.so
    - lib64/libmodem_svc_proto_legacy_soong.so
    - lib64/libril-aidl.so
    - lib64/libril_gfeature.so
    - lib64/libril_sitril.so
    - lib64/libsit_oem.so
    - lib64/libsit_oem_proto.so
    - lib64/libsitril-audio.so
    - lib64/libsitril-client.so
    - lib64/libsitril-gps.so
    - lib64/libsitril-ims.so
    - lib64/modem_android_property_manager_impl.so
    - lib64/modem_clock_manager_impl.so
    - lib64/modem_log_dumper.so
    - lib64/vendor.google.bluetooth_ext-V1-ndk.so
    - lib64/vendor.google.whitechapel.audio.audioext@4.0.so
    - lib64/vendor.google.whitechapel.audio.extension-V5-ndk.so
    - lib64/vendor.samsung_slsi.telephony.hardware.oemservice-V1-ndk.so
    - lib64/vendor.samsung_slsi.telephony.hardware.oemservice@1.0.so
    - lib64/vendor.samsung_slsi.telephony.hardware.radioExternal-V1-ndk.so
    - lib64/vendor.samsung_slsi.telephony.hardware.radioExternal@1.0.so
    - lib64/vendor.samsung_slsi.telephony.hardware.radioExternal@1.1.so
