platform:
  sepolicy_dirs:
    - device/google/gs201-sepolicy

includes:
  - pixel.yml
  - gs.yml

device:
  build_id: BP1A.250505.005.B1

filters:
  files:
    prefix:
      - product/lib/
      - system/framework/arm/
      - system/lib/
      - system_ext/lib/
      - vendor/lib/

    match:
      - system/bin/app_process32
      - system/bin/bootstrap/linker
      - system/bin/bootstrap/linker_asan
      - system/bin/boringssl_self_test32
      - system/bin/linker
      - system/bin/linker_asan
