includes:
  - pixel.yml

device:
  platform: gs201
  build_id: BP4A.251205.006

filters:
  file_exclusions:
    prefix:
      - product/lib/
      - system/framework/arm/
      - system/lib/
      - system_ext/lib/
      - vendor/lib/

    match:
      - system/bin/app_process32
      - system/bin/bootstrap/linker
      - system/bin/bootstrap/linker_asan
      - system/bin/boringssl_self_test32
      - system/bin/linker
      - system/bin/linker_asan
