includes:
  - apk.yml
  - backport.yml
  - file-exclusion.yml
  - file-inclusion.yml
  - kernel-cmdline.yml
  - overlay-inclusion.yml
  - overlay-removal.yml
  - replacement_modules.yml
  - sepolicy-inclusion.yml
  - sepolicy-exclusion.yml
  - synthetic-overlays.yml
  - sysconfig-exclusion.yml
  - sysconfig-inclusion.yml
  - sysprop-exclusion.yml
  - sysprop-inclusion.yml
  - vintf-inclusion.yml

device:
  vendor: google_devices
  system_fs_type: ext4
  has_cellular: true
  build_id: BP4A.251205.006
  backport_base_firmware: false

filters:
  partitions:
    match:
      - vbmeta_system
      - vbmeta_vendor
