includes:
  - file-removal.yml
  - overlay-inclusion.yml
  - overlay-removal.yml
  - removal.yml
  - synthetic-overlays.yml

device:
  vendor: google_devices
  system_fs_type: ext4
  kernel_repo_url: https://android.googlesource.com/kernel/common
  has_cellular: true
  build_id: BP2A.250805.005

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

filters:
  deprivileged_apks:
    prefix:
      - system_ext/priv-app/PixelNfc/
