sysprop_exclusions:
  - apexd.config.compressed_apex = true
  - dalvik.vm.allow_profile_code = true # TODO look further into this
  - dalvik.vm.isa.arm.features = default
  - dalvik.vm.isa.arm.variant = cortex-a53
  - dalvik.vm.isa.arm64.variant = cortex-a55
  - dalvik.vm.systemuicompilerfilter = speed
  - dalvik.vm.usejit = true
  - keyguard.no_require_sim = true
  - persist.arm64.memtag.app.com.android.nfc = off
  - persist.arm64.memtag.app.com.android.se = off
  - persist.arm64.memtag.app.com.google.android.bluetooth = off
  - persist.arm64.memtag.system_server = off
  - persist.sys.sf.native_mode = 2 # default display color mode
  - persist.vendor.factoryota.
  - persist.vendor.nfc.factoryota.
  - persist.vendor.pixellogger.
  - persist.vendor.tcpdump.log.alwayson
  - persist.vendor.wifi.perf_diag.file
  - persist.vendor.wifi.perf_diag.mode
  - persist.vendor.wifi.perf_diag.netperf
  - persist.vendor.wifi.perf_diag.period
  - persist.vendor.wifi.perf_diag.pid
  - pm.dexopt.ab-ota = speed-profile
  - pm.dexopt.bg-dexopt = speed-profile
  - pm.dexopt.boot-after-mainline-update = verify
  - pm.dexopt.boot-after-ota = verify
  - pm.dexopt.cmdline = verify
  - pm.dexopt.first-boot = verify
  - pm.dexopt.inactive = verify
  - pm.dexopt.install = speed-profile
  - pm.dexopt.install-bulk = speed-profile
  - pm.dexopt.install-bulk-downgraded = verify
  - pm.dexopt.install-bulk-secondary = verify
  - pm.dexopt.install-bulk-secondary-downgraded = verify
  - pm.dexopt.install-fast = skip
  - pm.dexopt.post-boot = verify
  - repair_mode.init_completed.
  - ro.arm64.memtag.bootctl_supported = 1
  - ro.atrace.core.services = com.google.android.gms,com.google.android.gms.ui,com.google.android.gms.persistent
  - ro.bionic.2nd_arch = arm
  - ro.bionic.2nd_cpu_variant = cortex-a53
  - ro.bionic.cpu_variant = cortex-a55
  - ro.boot.sota
  - ro.boot.sota.
  - ro.boot.vendor.overlay.theme = com.android.internal.systemui.navbar.gestural;com.google.android.systemui.gxoverlay
  - ro.build.date
  - ro.build.date.utc
  - ro.build.description
  - ro.build.display.id
  - ro.build.flavor = generic_system_google-user
  - ro.build.host
  - ro.build.id
  - ro.build.tags
  - ro.build.user
  - ro.build.version.base_os
  - ro.build.version.emergency_base_os # TODO look into it further
  - ro.build.version.incremental
  - ro.build.version.security_patch
  - ro.carriersetup.vzw_consent_page = true
  - ro.com.android.dataroaming = false
  - ro.com.android.prov_mobiledata = false
  - ro.com.google.clientidbase = android-google
  - ro.com.google.ime.height_ratio
  - ro.com.google.ime.kb_pad_port_b
  - ro.com.google.ime.kb_pad_port_l
  - ro.com.google.ime.kb_pad_port_r
  - ro.com.google.ime.system_lm_dir = /product/usr/share/ime/google/d3_lms
  - ro.com.google.ime.theme_id = 5
  - ro.config.alarm_alert = Fresh_start.ogg
  - ro.config.notification_sound = Eureka.ogg
  - ro.config.ringtone = Your_new_adventure.ogg
  - ro.error.receiver.system.apps = com.google.android.gms
  - ro.hotword.detection_service_required = false
  - ro.odm.build.date
  - ro.odm.build.date.utc
  - ro.odm.build.fingerprint
  - ro.odm.build.id
  - ro.odm.build.id
  - ro.odm.build.tags
  - ro.odm.build.version.incremental
  - ro.odm_dlkm.build.date
  - ro.odm_dlkm.build.date.utc
  - ro.odm_dlkm.build.fingerprint
  - ro.odm_dlkm.build.id
  - ro.odm_dlkm.build.tags
  - ro.odm_dlkm.build.version.incremental
  - ro.product.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gcf,gsa,gsa_bl1,init_boot,ldfw,modem,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot # handled elsewhere
  - ro.product.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gsa,init_boot,ldfw,modem,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot
  - ro.product.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gsa,init_boot,ldfw,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot
  - ro.product.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gsa,ldfw,modem,pbl,product,system,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm
  - ro.product.build.16k_page.enabled = true
  - ro.product.build.date
  - ro.product.build.date.utc
  - ro.product.build.fingerprint
  - ro.product.build.id
  - ro.product.build.tags
  - ro.product.build.version.incremental
  - ro.product.system.brand = google # dynamically generated by the build system
  - ro.product.system.manufacturer = Google # dynamically generated by the build system
  - ro.product.system.model = Generic System
  - ro.product.system.name = generic_system_google
  - ro.scone.relay_metrics_default_enable = 1
  - ro.setupwizard.enterprise_mode = 1
  - ro.setupwizard.esim_cid_ignore = 00000001
  - ro.storage_manager.enabled = false
  - ro.storage_manager.show_opt_in = false
  - ro.system.build.date
  - ro.system.build.date.utc
  - ro.system.build.fingerprint
  - ro.system.build.id
  - ro.system.build.tags
  - ro.system.build.version.incremental
  - ro.system_dlkm.build.date
  - ro.system_dlkm.build.date.utc
  - ro.system_dlkm.build.fingerprint
  - ro.system_dlkm.build.id
  - ro.system_dlkm.build.tags
  - ro.system_dlkm.build.version.incremental
  - ro.system_ext.build.date
  - ro.system_ext.build.date.utc
  - ro.system_ext.build.fingerprint
  - ro.system_ext.build.id
  - ro.system_ext.build.tags
  - ro.system_ext.build.version.incremental
  - ro.usb.data_protection.disable_when_locked.supported = true
  - ro.vendor.build.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gcf,gsa,gsa_bl1,init_boot,ldfw,modem,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot # handled elsewhere
  - ro.vendor.build.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gsa,init_boot,ldfw,modem,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot
  - ro.vendor.build.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gsa,init_boot,ldfw,pbl,product,pvmfw,system,system_dlkm,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,vendor_kernel_boot
  - ro.vendor.build.ab_ota_partitions = abl,bl1,bl2,bl31,boot,dtbo,gsa,ldfw,modem,pbl,product,system,system_ext,tzsw,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm
  - ro.vendor.build.date
  - ro.vendor.build.date.utc
  - ro.vendor.build.fingerprint
  - ro.vendor.build.id
  - ro.vendor.build.security_patch
  - ro.vendor.build.tags
  - ro.vendor.build.version.incremental
  - ro.vendor.config.build_carrier
  - ro.vendor_dlkm.build.date
  - ro.vendor_dlkm.build.date.utc
  - ro.vendor_dlkm.build.fingerprint
  - ro.vendor_dlkm.build.id
  - ro.vendor_dlkm.build.tags
  - ro.vendor_dlkm.build.version.incremental
  - setupwizard.feature.baseline_setupwizard_enabled = true
  - setupwizard.feature.day_night_mode_enabled = true
  - setupwizard.feature.default_locale_enhancement_enabled = true
  - setupwizard.feature.enable_force_two_pane = true
  - setupwizard.feature.enable_gil =
  - setupwizard.feature.enable_minors_setup_flow = true
  - setupwizard.feature.enable_parental_notice_activity = true
  - setupwizard.feature.enable_parental_setup = true
  - setupwizard.feature.enable_quick_start_flow = true
  - setupwizard.feature.enable_restore_anytime = true
  - setupwizard.feature.enable_tween_setup_flow = true
  - setupwizard.feature.enable_wifi_tracker = true
  - setupwizard.feature.lifecycle_refactoring = true
  - setupwizard.feature.locale_agnostic_enabled = true
  - setupwizard.feature.notification_refactoring = true
  - setupwizard.feature.portal_notification = true
  - setupwizard.feature.provisioning_profile_mode
  - setupwizard.feature.provisioning_profile_mode = true
  - setupwizard.feature.show_digital_warranty = true
  - setupwizard.feature.show_pai_screen_in_main_flow.carrier1839 = false
  - setupwizard.feature.show_pixel_tos = true
  - setupwizard.feature.show_support_link_in_deferred_setup = false
  - setupwizard.feature.skip_button_use_mobile_data.carrier1839 = true
  - setupwizard.personal_safety_suw_enabled = true
  - setupwizard.personal_safety_suw_satellite_sos_visible = false
  - setupwizard.theme = glif_expressive # TODO switch to glif_expressive in base OS
  - sota.charge.stop.level
  - vendor.audiodump.cca.config
  - vendor.audiodump.enable
  - vendor.audiodump.encode.disable
  - vendor.audiodump.log.cca.updated
  - vendor.audiodump.log.config
  - vendor.audiodump.log.ondemand
  - vendor.audiodump.output.dir
  - vendor.debug.ramdump.
  - vendor.debug.ssrdump.
  - vendor.debug.ssrdump.type
  - vendor.pixel.system.phenotype.
  - vendor.pixellogger.
  - vendor.tcpdump.
  - vendor.tcpdump.log.alwayson
  - vendor.tcpdump.log.ondemand
  - vendor.tcpdump.output.dir
