vintf_manifest_inclusions:
  vendor:
    - <kernel target-level="6"/>
    - |-
      <sepolicy>
        <version>202504</version>
      </sepolicy>

vintf_inclusions:
  - vendor.google.ambience_hub.IAmbienceHubConsumerManager/default
  - vendor.google.ambience_hub.IAmbienceHubProducerManager/default
  - android.frameworks.displayservice::IDisplayService/default
  - android.frameworks.schedulerservice::ISchedulingPolicyService/default
  - android.frameworks.sensorservice::ISensorManager/default
  - android.hardware.audio.core.IConfig/default
  - android.hardware.audio.core.IModule/bluetooth
  - android.hardware.audio.core.IModule/default
  - android.hardware.audio.core.IModule/r_submix
  - android.hardware.audio.effect.IFactory/default
  - android.hardware.audio.effect::IEffectsFactory/default
  - android.hardware.audio::IDevicesFactory/default
  - android.hardware.authsecret.IAuthSecret/default
  - android.hardware.biometrics.fingerprint.IFingerprint/default
  - android.hardware.bluetooth.finder.IBluetoothFinder/default
  - android.hardware.bluetooth.IBluetoothHci/default
  - android.hardware.bluetooth.ranging.IBluetoothChannelSounding/default
  - android.hardware.bluetooth::IBluetoothHci/default
  - android.hardware.boot.IBootControl/default
  - android.hardware.camera.provider.ICameraProvider/internal/0
  - android.hardware.contexthub.IContextHub/default
  - android.hardware.drm.IDrmFactory/castkey
  - android.hardware.dumpstate.IDumpstateDevice/default
  - android.hardware.gnss.IGnss/default
  - android.hardware.gnss.IGnss/vendor
  - android.hardware.graphics.allocator.IAllocator/default
  - android.hardware.graphics.composer3.IComposer/default
  - android.hardware.graphics.composer::IComposer/default
  - android.hardware.graphics.composer::IComposer/vr
  - android.hardware.health.IHealth/default
  - android.hardware.input.processor.IInputProcessor/default
  - android.hardware.light.ILights/default
  - android.hardware.media.c2.IComponentStore/default
  - android.hardware.media.c2.IComponentStore/default1
  - android.hardware.media.c2.IComponentStore/default2
  - android.hardware.media.omx::IOmx/default
  - android.hardware.media.omx::IOmxStore/default
  - android.hardware.memtrack.IMemtrack/default
  - android.hardware.neuralnetworks.IDevice/google-edgetpu
  - android.hardware.oemlock.IOemLock/default
  - android.hardware.power.IPower/default
  - android.hardware.power.stats.IPowerStats/default
  - android.hardware.radio.config.IRadioConfig/default
  - android.hardware.radio.config::IRadioConfig/default
  - android.hardware.radio.data.IRadioData/slot1
  - android.hardware.radio.data.IRadioData/slot2
  - android.hardware.radio.messaging.IRadioMessaging/slot1
  - android.hardware.radio.messaging.IRadioMessaging/slot2
  - android.hardware.radio.modem.IRadioModem/slot1
  - android.hardware.radio.modem.IRadioModem/slot2
  - android.hardware.radio.network.IRadioNetwork/slot1
  - android.hardware.radio.network.IRadioNetwork/slot2
  - android.hardware.radio.sap.ISap/slot1
  - android.hardware.radio.sap.ISap/slot2
  - android.hardware.radio.sim.IRadioSim/slot1
  - android.hardware.radio.sim.IRadioSim/slot2
  - android.hardware.radio.voice.IRadioVoice/slot1
  - android.hardware.radio.voice.IRadioVoice/slot2
  - android.hardware.radio::IRadio/slot1
  - android.hardware.radio::IRadio/slot2
  - android.hardware.radio::ISap/slot1
  - android.hardware.radio::ISap/slot2
  - android.hardware.secure_element.ISecureElement/SIM1
  - android.hardware.secure_element.ISecureElement/SIM2
  - android.hardware.secure_element::ISecureElement/eSE1
  - android.hardware.secure_element::ISecureElement/eSE2
  - android.hardware.secure_element::ISecureElement/SIM1
  - android.hardware.secure_element::ISecureElement/SIM2
  - android.hardware.security.keymint.IKeyMintDevice/strongbox
  - android.hardware.security.keymint.IRemotelyProvisionedComponent/strongbox
  - android.hardware.security.sharedsecret.ISharedSecret/strongbox
  - android.hardware.soundtrigger3.ISoundTriggerHw/default
  - android.hardware.soundtrigger::ISoundTriggerHw/default
  - android.hardware.tetheroffload.config::IOffloadConfig/default
  - android.hardware.tetheroffload.control::IOffloadControl/default
  - android.hardware.thermal.IThermal/default
  - android.hardware.usb.gadget.IUsbGadget/default
  - android.hardware.usb.IUsb/default
  - android.hardware.uwb.IUwb/default
  - android.hardware.vibrator.IVibrator/default
  - android.hardware.vibrator.IVibrator/dual
  - android.hardware.weaver.IWeaver/default
  - android.hardware.wifi.hostapd.IHostapd/default
  - android.hidl.allocator::IAllocator/ashmem
  - android.hidl.memory::IMapper/ashmem
  - android.hidl.token::ITokenManager/default
  - android.system.wifi.keystore::IKeystore/default
  - android.vendor.samsung_slsi.telephony.hardware.radio::IOemSamsungslsi/slot1
  - android.vendor.samsung_slsi.telephony.hardware.radio::IOemSamsungslsi/slot2
  - aocx.IAocx/default
  - com.fingerprints33.extension::IFingerprintAuthenticator/default
  - com.fingerprints33.extension::IFingerprintCalibration/default
  - com.fingerprints33.extension::IFingerprintEngineering/default
  - com.fingerprints33.extension::IFingerprintNavigation/default
  - com.fingerprints33.extension::IFingerprintRecalibration/default
  - com.fingerprints33.extension::IFingerprintSenseTouch/default
  - com.fingerprints33.extension::IFingerprintSensorTest/default
  - com.fingerprints42.extension::IFingerprintAuthenticator/default
  - com.fingerprints42.extension::IFingerprintCalibration/default
  - com.fingerprints42.extension::IFingerprintEngineering/default
  - com.fingerprints42.extension::IFingerprintNavigation/default
  - com.fingerprints42.extension::IFingerprintRecalibration/default
  - com.fingerprints42.extension::IFingerprintSenseTouch/default
  - com.fingerprints42.extension::IFingerprintSensorTest/default
  - com.google.android.imageprocessing.hal.IImageProcessingHal/default
  - com.google.edgetpu.dba.IDevice/default
  - com.google.edgetpu.IEdgeTpuAppService/default
  - com.google.edgetpu.IEdgeTpuVendorService/default
  - com.google.edgetpu.tachyon.IComputeService/default
  - com.google.face.debug.IDebugHost/default
  - com.google.face.debug.IDebugManager/default
  - com.google.flood.IFloodService/default
  - com.google.hardware.biometrics.fingerprint.debug.IFingerprintDebug/default
  - com.google.hardware.pixel.display.IDisplay/default
  - com.google.hardware.pixel.display.IDisplay/secondary
  - com.google.input.algos.gril.IGrilAntennaTuningService/default
  - com.google.input.algos.spd.IScreenProtectorDetectorService/default
  - com.google.input.gia.core.IGiaService/default
  - com.google.input.ITouchContextService/default
  - com.google.input.ITwoshayFileDumpService/touchflow_default
  - com.google.input.ITwoshayFileDumpService/touchflow_outer
  - com.google.input.ITwoshayFileDumpService/twoshay
  - com.google.input.ITwoshayNotificationService/default
  - com.google.pixel.camera.connectivity.hal.provider.ICameraProvider/default
  - com.google.pixel.camera.services.binder.IServiceBinder/default
  - com.google.pixel.camera.services.cameraidremapper.ICameraIdRemapper/default
  - com.google.pixel.camera.services.lyricconfigprovider.ILyricConfigProvider/default
  - com.google.pixel.modem.logmasklibrary.ILiboemserviceProxy/default
  - com.google.pixel.moseyservice.IMoseyService/default
  - com.google.pixel.shared_modem_platform.ISharedModemPlatform/default
  - hardware.google.bluetooth.bt_channel_avoidance::IBTChannelAvoidance/default
  - hardware.google.bluetooth.ccc::IBluetoothCcc/default
  - hardware.google.bluetooth.ext::IBluetoothExt/default
  - hardware.google.bluetooth.sar::IBluetoothSar/default
  - hardware.google.ril_ext.IRilExt/slot1
  - hardware.google.ril_ext.IRilExt/slot2
  - hardware.qorvo.uwb.IUwbVendor/default
  - mapper.@5.0/pixel
  - vendor.goodix.hardware.biometrics.fingerprint::IGoodixFingerprintDaemon/default
  - vendor.google.aam.IAam/default
  - vendor.google.audiometricext::IAudioMetricExt/default
  - vendor.google.battery_mitigation.IBatteryMitigation/default
  - vendor.google.bluetooth_ext.IBluetoothCcc/default
  - vendor.google.bluetooth_ext.IBluetoothCco/default
  - vendor.google.bluetooth_ext.IBluetoothEwp/default
  - vendor.google.bluetooth_ext.IBluetoothExt/default
  - vendor.google.bluetooth_ext.IBluetoothFinder/default
  - vendor.google.bluetooth_ext.IBluetoothSar/default
  - vendor.google.bluetooth_ext.IBTChannelAvoidance/default
  - vendor.google.google_battery.IGoogleBattery/default
  - vendor.google.radio_ext.IRadioExt/default
  - vendor.google.radioext::IRadioExt/default
  - vendor.google.whitechapel.audio.audioext::IAudioExt/default
  - vendor.google.whitechapel.audio.extension.IAudioExtension/default
  - vendor.google.wifi_ext.IWifiExt/default
  - vendor.google.wireless_charger.IWirelessCharger/default
  - vendor.google.wireless_charger.service.IWlcService/default
  - vendor.qti.hardware.fingerprint.IQfpExtendedFingerprint/default
  - vendor.qti.hardware.fingerprint.IQfpExtendedSession/default
  - vendor.qti.hardware.fingerprint.IQfpExtendedSessionCallback/default
  - vendor.samsung_slsi.telephony.hardware.oemservice.IOemService/dm0
  - vendor.samsung_slsi.telephony.hardware.oemservice.IOemService/dm1
  - vendor.samsung_slsi.telephony.hardware.oemservice.IOemService/sced0
  - vendor.samsung_slsi.telephony.hardware.oemservice::IOemService/dm0
  - vendor.samsung_slsi.telephony.hardware.oemservice::IOemService/dm1
  - vendor.samsung_slsi.telephony.hardware.oemservice::IOemService/sced0
  - vendor.samsung_slsi.telephony.hardware.radioExternal.IOemSlsiRadioExternal/default
  - vendor.samsung_slsi.telephony.hardware.radioExternal::IOemSlsiRadioExternal/rilExternal
  - android.hardware.security.secretkeeper.ISecretkeeper/default
  - android.hardware.drm.IDrmFactory/clearkey
  - android.hardware.sensors.ISensors/default
  - android.hardware.wifi.supplicant.ISupplicant/default
  - android.hardware.health.storage.IStorage/default
  - android.hardware.nfc.INfc/default
